#   
#                                                                                                                                                              
#  ,----..                                   ___                                ,---,    ___                       ____               
# /   /   \                                ,--.'|_    ,--,                   ,`--.' |  ,--.'|_                   ,'  , `.             
#|   :     :  __  ,-.                      |  | :,' ,--.'|                   |   :  :  |  | :,'               ,-+-,.' _ |             
#.   |  ;. /,' ,'/ /|                      :  : ' : |  |,      .---.         :   |  '  :  : ' :            ,-+-. ;   , ||  .--.--.    
#.   ; /--` '  | |' | ,---.     ,--.--.  .;__,'  /  `--'_    /.  ./|  ,---.  |   :  |.;__,'  /     ,---.  ,--.'|'   |  || /  /    '   
#;   | ;    |  |   ,'/     \   /       \ |  |   |   ,' ,'| .-' . ' | /     \ '   '  ;|  |   |     /     \|   |  ,', |  |,|  :  /`./   
#|   : |    '  :  / /    /  | .--.  .-. |:__,'| :   '  | |/___/ \: |/    /  ||   |  |:__,'| :    /    /  |   | /  | |--' |  :  ;_     
#.   | '___ |  | ' .    ' / |  \__\/: . .  '  : |__ |  | :.   \  ' .    ' / |'   :  ;  '  : |__ .    ' / |   : |  | ,     \  \    `.  
#'   ; : .'|;  : | '   ;   /|  ," .--.; |  |  | '.'|'  : |_\   \   '   ;   /||   |  '  |  | '.'|'   ;   /|   : |  |/       `----.   \ 
#'   | '/  :|  , ; '   |  / | /  /  ,.  |  ;  :    ;|  | '.'\   \  '   |  / |'   :  |  ;  :    ;'   |  / |   | |`-'       /  /`--'  / 
#|   :    /  ---'  |   :    |;  :   .'   \ |  ,   / ;  :    ;\   \ |   :    |;   |.'   |  ,   / |   :    |   ;/          '--'.     /  
# \   \ .'          \   \  / |  ,     .-./  ---`-'  |  ,   /  '---" \   \  / '---'      ---`-'   \   \  /'---'             `--'---'   
#  `---`             `----'   `--`---'               ---`-'          `----'                       `----'                                                                             
#,-.----.                                       
#\    /  \    ,--,                              
#|   :    \ ,--.'|                              
#|   |  .\ :|  | :            ,--,              
#.   :  |: |:  : '          ,'_ /|   .--.--.    
#|   |   \ :|  ' |     .--. |  | :  /  /    '   
#|   : .   /'  | |   ,'_ /| :  . | |  :  /`./   
#;   | |`-' |  | :   |  ' | |  . . |  :  ;_     
#|   | ;    '  : |__ |  | ' |  | |  \  \    `.  
#:   ' |    |  | '.'|:  | : ;  ; |   `----.   \ 
#:   : :    ;  :    ;'  :  `--'   \ /  /`--'  / 
#|   | :    |  ,   / :  ,      .-./'--'.     /  
#`---'.|     ---`-'   `--`----'      `--'---'   
#  `---`                                        
                                                                                                                                                                               
#If enabled, all items are wiped except ones you've added
full-customization: false
#Items you want added (Format: itemid:damagevalue)
items-added:
  246: 0 #Glowing obsidian
  247: 1 #Red Nether Reactor Core
  247: 2 #Black Nether Reactor Core
#Items you want removed (Format: itemid:damagevalue)
items-removed:
  46: 0 #Tnt
  259: 0 #Flint & Steel

